from ItemsClass import Items

potion = Items("Potion")
recov = Items("Recovery")
medh = Items("Medicinal Herb")
hw = Items("Holy Water")
cs = Items("Copper Sword")
ws = Items("Wooden Shield")
oa = Items("Old Axe")
ha = Items("Hunter's Axe")
rs = Items("Rusted Shield")
irons = Items("Iron Sword")
ls = Items("Leather Shield")
ga = Items("Grand Axe")
sb = Items("Standard Bow")
lb = Items("Long Bow")
ss = Items("Scale Shield")
